package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/bresilla/drop/src/pkg/conf"
	"github.com/bresilla/drop/src/pkg/vault"
)

func newVaultCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "vault",
		Short: "Whether what is kept on this disk is encrypted",
		Long: "Conversations are written to disk. Without a vault they are written in the clear,\n" +
			"and 0600 under 0700 stops another account on this machine and nothing else.\n\n" +
			"A vault encrypts them with a data key of its own, wrapped to whoever you name in\n" +
			"drop.vault. It protects a machine that is off — a stolen laptop, a pulled disk, a\n" +
			"leaked backup. It cannot protect a machine that is running: drop has to read the\n" +
			"data to show it to you, so anything with your session can ask drop.",
		Args: cobra.NoArgs,
		RunE: func(*cobra.Command, []string) error {
			return showVault()
		},
	}
}

// showVault reports, and creates nothing. Asking what a vault is doing must not be what sets one
// up: a key generated by a question is a key nobody knows they have.
func showVault() error {
	cfg, err := conf.Load()
	if err != nil {
		return err
	}
	defer cfg.Close()

	at, err := vault.Peek(cfg.Vault)
	if err != nil {
		return err
	}

	if at == vault.Off {
		fmt.Println("\n  off — what is kept on this disk is in the clear")
		fmt.Println("\n  set drop.vault in your config to change that:")
		fmt.Println("    drop.vault = \"~/.config/drop/vault.key\"    protects a backup, not a live disk")
		fmt.Println("    drop.vault = { \"age1yubikey1…\", \"age1…\" }  unreadable without the key")
		fmt.Println()
		return nil
	}

	fmt.Printf("\n  wrapped to\n")
	for _, to := range cfg.Vault {
		fmt.Printf("    %s\n", to)
	}

	switch at {
	case vault.Fresh:
		fmt.Printf("\n  not set up yet — the data key is made the next time drop serves\n")
		fmt.Printf("  what is on this disk now is still in the clear.\n\n")
	case vault.Locked:
		fmt.Printf("\n  locked — the data key cannot be unwrapped here\n")
		fmt.Printf("  what is on this disk is there and unreadable, not gone.\n\n")
	default:
		fmt.Printf("\n  open — the data key is held while drop runs\n\n")
	}
	return nil
}
